# -*- coding: utf-8 -*-
"""AlmacenRogelioAlejandroFaustinoSierra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sg8E2DdufVACzTL7DYw_FXiyrIVjypVA
"""

from google.colab import drive
drive.mount("/content/drive")

#se debe instalar reportlab y pandas con !pip install pandas y !pip install reportlab. En este caso es recomendable para la instalación de archivos, librerias y la correcta ejecución, ejecutar este código en colab.

import pandas as pd
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

def Imprimir(archivo5,file): #imprimir en pdf
  if file != "Productos" and file != "Producto":
    lista = [80,70,210,140,140]
  elif file == "Productos" or file == "Producto":
    lista = [260,60,60,60,60]

  pdf_file = f'{file}.pdf'
  pdf = SimpleDocTemplate(pdf_file, pagesize=letter)
  elements = []


  data = [archivo5.columns.tolist()] + archivo5.values.tolist()

  table = Table(data, colWidths= lista, rowHeights=15)
  table.setStyle(TableStyle([
  ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
  ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
  ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
  ('GRID', (0, 0), (-1, -1), 1, colors.black),
  ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
  ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
  ('FONTSIZE', (0, 0), (-1, -1), 4),
  ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ]))

  elements.append(table)
  pdf.build(elements)

  print("Tu pdf se ha generado")

def Alta(archivo,file):
  Puntuacion=",.*_:;=¨+{}&<>$!?¿¡[]@"
  correo = ",*:;=+'{}><$!?¿¡[]"
  Acentos = "áéíóúÁÉÍÓÚ"
  Num = "1234567890"
  op = ""
  letra = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z', 'J']
  var2= ""
  cont = 0

  print(f"Alta nuevo {file}")

  while op != "no":

    var = ""
    if file != "Productos":

      lista1 = archivo["RFC"].tolist()
      RFC = input(f"introduce el rfc del nuevo {file}:").strip()
      for i in RFC:
        if i in Acentos or i in Puntuacion:
           print("\nNo introduzcas caracteres invalidos, intentalo de nuevo\n")
           var = "F"
           break
      if var == "F":
        continue
      if len(RFC) < 12 or len(RFC) > 13:
        print("\nIntroduce un RFC valido, intentalo de nuevo\n")
        continue
      if RFC in lista1:
        print("\nEste RFC ya fue capturado, intentalo de nuevo\n")
        continue
      for i in letra:
        if i in RFC[4:10].upper():
          print("\ntiene que haber 4 letras al principio, intentalo de nuevo\n")
          var2 = "FF"
          break

      for i in Num:
        if i in RFC[0:3]:
          print("\nNo puede haber numeros al principio, intentalo de nuevo\n")
          var2 = "FF"
          break
      if var2 == "FF":
        continue

      while True:
        var = ""
        Nombre = input(f"introduce el nombre del nuevo {file} :")
        for i in Nombre:
          if i in Acentos or i in Puntuacion or i in Num:
            print("\nNo introduzcas caracteres invalidos, intentalo de nuevo\n")
            var = "F"
            break
        if var == "F":
          continue
        break
      while True:
        var = ""
        Dir = input(f"introduce la direccion del nuevo {file} :")
        for i in Dir:
          if i in Acentos:
            print("\nNo introduzcas caracteres invalidos, intentalo de nuevo\n")
            var = "F"
            break
          if var == "F":
            continue
        break
      while True:
        try:
          Telefono = int(input(f"introduce el numero de telefono del nuevo {file} :"))
          pass
        except ValueError:
          print("\nNo introduzcas caracteres o puntos decimales, intentalo de nuevo\n")
          continue
        if Telefono < 0:
          print("\nno introduzcas valores negativos,intentalo de nuevo\n")
          continue
        break
      while True:
        var = ""
        Correo = input(f"introduce el correo del nuevo {file} :")
        for i in Correo:
          if i in Acentos or i in correo:
            print("\nNo introduzcas acentos o caracteres invalidos, intentalo de nuevo\n")
            var = "F"
            break
        if var == "F":
          continue
        if Correo.count("@") > 1 or Correo.count("@") < 1 or Correo.count(".") > 1 or Correo.count(".") < 1 or correo.count("_") > 1:
          print("\nIntroduce un formato de correo valido\n")
          continue
        break



      archivo.loc[len(archivo)] = [RFC.upper(),Nombre.title(),Dir,Telefono,Correo.strip()]
      print("\nUsuario Agregado\n")

      op = input(f"¿Quieres agregar otro {file} (si/no) : ")


    elif file == "Productos":

      lista = archivo["CODIGO_BARRAS"].tolist()
      try:
        Codigo = int(input("introduce el codigo de barras :"))
      except ValueError:
        print("\nIntroduce un codigo de barras valido con numeros enteros, intentalo de nuevo\n")
        continue
      if Codigo in lista:
        print("\nEste codigo ya existe, intentalo de nuevo\n")
        continue
      if Codigo < 0:
        print("\nNo puede ser negativo, intentalo de nuevo\n")
      while True:
        var = ""
        NP = input("introduce la descripcion del nuevo producto :")
        for i in NP:
          if i in Acentos:
            print("\nNo introduzcas acentos\n")
            var = "F"
            break
        if var == "F":
          continue
        break
      while True:
        try:
          P = float(input("introduce el precio del producto :"))
        except ValueError:
          print("\nIntroduce solo valores numericos, intentalo de nuevo\n")
          continue
        if P < 0:
          print("\nNo puede haber valores negativos, intentalo de nuevo\n")
          continue
        break

      while True:
        try:
          Cant = int(input("introduce su cantidad :"))
        except ValueError:
          print("\nIntroduce valores numericos enteros, intentalo de nuevo\n")

        if Cant <1:
          print("\nNo puede haber stock negativo o menor a uno, intentalo de nuevo\n")
          continue
        break

      inversion = P * Cant

      archivo.loc[len(archivo)] = [NP,P,Codigo,Cant,inversion]
      op = input("¿Quieres agregar otro producto? (si/no) :")

      print("\nProducto agregado\n")
      break
  return archivo

def Eliminar(archivo2,file):

  print("Eliminar producto")
  if file != "Productos":
    while True:
      listaRFC = archivo2["RFC"].tolist()
      RFC = (input(f"introduce el RFC para saber que {file} eliminar :")).upper().strip()
      if RFC in listaRFC:
        index = listaRFC.index(RFC)
        user = archivo2.loc[(archivo2["RFC"] == RFC)]

        print(user)
        preg = input("¿seguro que quieres borrar a este usuario? (si/no) :")
        if preg.lower() != "si":
          print("\nintentalo de nuevo o selecciona otra opcion\n")
          break
        for i in archivo2["RFC"]:
          if i == RFC and preg.lower() == "si":
            archivo2.drop([index], axis = 0, inplace= True)
            print("\nUsuario eliminado\n")
            break
        break


      else:
        print("\nEste RFC no existe o no es valido, intenta de nuevo\n")
        continue

  elif file == "Productos":
    while True:
      lista = archivo2["CODIGO_BARRAS"].tolist()
      try:
        CodigoBarras = int(input("introduce el codigo de barras para saber que producto eliminar :"))
      except ValueError:
        print("Introduce un codigo de barras valido")
        continue

      if CodigoBarras in lista:
        indice = lista.index(CodigoBarras)
        prod = archivo2.loc[(archivo2["CODIGO_BARRAS"] == CodigoBarras)]

        print(prod)
        preg = input("¿seguro que quieres borrar este producto? (si/no) :")
        if preg.lower() != "si":
          print("intentalo de nuevo o selecciona otra opcion")
          break
        for i in archivo2["CODIGO_BARRAS"]:
          if i == CodigoBarras and preg.lower() == "si":
            archivo2.drop([indice], axis = 0, inplace= True)
            print("\nProducto eliminado\n")
            break
        break

      else:
        print("\nEste codigo de barras no existe o no es valido, intentalo de nuevo\n")
        continue

  return archivo2

def Modificar(archivo3,dato,file):

  var = ""
  var2 = ""
  Num = "1234567890"
  Puntuacion = ",.*_:;=¨+{}&<>$!@"
  correo = ",*:;=+'{}><$!?¿¡[]"
  Acentos = "áéíóúÁÉÍÓÚ"
  letra = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z', 'J']
  if file != "Productos":
    while True:
      RFC = (input(f"introduce el RFC para saber que {file} es :")).upper().strip()
      listaRFC = archivo3["RFC"].tolist()

      if RFC in listaRFC:
        while True:
          var = ""
          var2 = ""
          if dato == "RFC":
            P = input(f"introduce el nuevo {dato} :").upper().strip()

            for i in P:
              if i in Acentos or i in Puntuacion:
                print("\nNo introduzcas caracteres invalidos, intentalo de nuevo\n")
                var = "F"
                break

            if var == "F":
              continue

            if len(P) < 12 or len(P) > 13:
              print("\nIntroduce un RFC valido, intentalo de nuevo\n")
              continue

            if P in listaRFC:
              print("\nEste RFC ya fue capturado, intentalo de nuevo\n")
              continue
            for i in letra:
              if i in P[4:11].upper():
                print("\ntiene que haber 4 letras al principio, intentalo de nuevo\n")
                var2 = "FF"
                break

            for i in Num:
              if i in P[0:3]:
                print("\nNo puede haber numeros al principio, intentalo de nuevo\n")
                var2 = "FF"
                break
            if var2 == "FF":
              continue
            break

          elif dato == "NOMBRE":
            P = input(f"introduce el nuevo {dato} :").title()
            for i in P:
              if i in Acentos or i in Puntuacion or i in Num:
                print("\nNo introduzcas caracteres invalidos, intentalo de nuevo\n")
                var = "F"
                break
            if var == "F":
              continue

          elif dato == "DIRECCION":
            P = input(f"Introduce la nueva {dato} :")
            for i in P:
              if i in Acentos:
                print("\nNo introduzcas caracteres invalidos, intentalo de nuevo\n")
                var = "F"
                break
            if var == "F":
              continue

          elif dato == "NUMERO":
            try:
              P = int(input(f"introduce el nuevo {dato} :"))
            except ValueError:
              print("introduce un valor valido, intentalo de nuevo")
              continue
            if P < 0:
              print("no introduzcas valores negativos")
              continue

          elif dato == "CORREO":
            P = input(f"introduce el nuevo {dato} :")
            for i in P:
              if i in Acentos or i in correo:
                print("\nNo introduzcas acentos o caracteres invalidos, intentalo de nuevo\n")
                var = "F"
                break
            if var == "F":
              continue

            if P.count("@") > 1 or P.count("@") < 1 or P.count(".") > 1 or P.count(".") < 1 or P.count("_") > 1:
              print("\nIntroduce un formato de correo valido\n")
              continue


          print("\nDataframe modificado\n")
          archivo3.loc[(archivo3["RFC"] == RFC), dato] = P
          break
      else:
        print("este RFC no existe, intentalo de nuevo :")
        continue

      break

    return archivo3
  elif file == "Productos":
    while True:
      var = ""
      try:
        CodigoBarras = int(input("introduce el codigo de barras para saber que producto es :"))
      except ValueError:
        print("codigo invalido, intentalo de nuevo")
        continue
      lista = archivo3["CODIGO_BARRAS"].tolist()
      if CodigoBarras in lista:
       while True:
        if dato == "CODIGO_BARRAS":
          try:
            Codigo = int(input("introduce el nuevo codigo de barras :"))
          except ValueError:
            print("\nIntroduce un codigo de barras valido con numeros\n")
            continue

          if Codigo < 0:
            print("\nNo puede ser negativo, intentalo de nuevo\n")
            continue
          if Codigo in lista:
            print("\nEste codigo ya existe, intentalo de nuevo\n")
            continue

          archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras),dato] = Codigo

        elif dato == "DESCRIPCION":
          NP = input("introduce la descripcion del nuevo producto :")
          for i in NP:
            if i in Acentos:
              print("\nNo introduzcas acentos\n")
              var = "F"
              break
          if var == "F":
            continue
          archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras),dato] = NP
        elif dato == "PRECIO":
          try:
            V = float(input("introduce el precio nuevo :"))
          except ValueError:
            print("\nvalor invalido, intentalo de nuevo\n")
            continue

            if V < 0:
              print("\nintroduce valores mayores a 0\n")
              continue

          dato2 = archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras), "Stock"]
          inversion_nueva = dato2 * V
          archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras), "Inversion"] = inversion_nueva
          archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras), dato] = V
          print("\nArchivo modificado\n")
          break

        elif dato == "Stock":
          try:
            V = int(input("introduce el nuevo stock del producto :"))
          except ValueError:
            print("\nvalor invalido, intentalo de nuevo\n")
            continue

          if V < 1:
            print("\nNo puede haber stocks menores a uno\n")
            continue

          dato2 = archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras), "PRECIO"]
          inversion_nueva = dato2 * V
          archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras), "Inversion"] = inversion_nueva

          archivo3.loc[(archivo3["CODIGO_BARRAS"] == CodigoBarras), dato] = V
          print("\nArchivo modificado\n")
          break

      else:
        print("\nCodigo de barras inexistente, intentalo de nuevo\n")
        continue
      break
  return archivo3

def Buscar(archivo4, tipo,file):

  cont = 0
  cont2 = 0
  if tipo == "NOMBRE":
    lista = archivo4["NOMBRE"].tolist()
    N = input(f"Introduce el nombre del {file} (empieza con un asterisco (*) para buscarlo por la primera letra) :")
    if N.startswith("*") == True and len(N) == 2:
      for i in N:
        cont2 += 1
        if cont2 == 2:
          letra = i
      for i in lista:
        if i.lower().startswith(letra):
          Fila = archivo4.loc[(archivo4["NOMBRE"] == i)]
          print(f"\n{Fila}\n")
          cont += 1


    else:
      for i in lista:
        if N.lower() in i.lower():
          Fila = archivo4.loc[(archivo4["NOMBRE"] == i)]
          print(f"\n{Fila}\n")
          cont += 1
    print(f"\nHay {cont} {file} que coinciden con ese nombre\n")

  if tipo == "RFC":
    while True:
      lista2 = archivo4["RFC"].tolist()

      RFC = input(f"introduce el RFC del {file}:").upper().strip()
      if RFC in lista2:
        Fila = archivo4.loc[(archivo4["RFC"] == RFC)]
        print(f"\n{Fila}\n")
        break
      else:
        print("\nEste codigo RFC no existe, intentalo de nuevo\n")
        continue
  if tipo == "Nombre":
    lista3 = archivo4["DESCRIPCION"].tolist()
    N = input(f"Introduce el nombre del {file} (empieza con un asterisco (*) para buscarlo por la primera letra) :")
    if N.startswith("*") == True and len(N) == 2:
      for i in N:
        cont2 += 1
        if cont2 == 2:
          letra = i
      for i in lista3:
        if i.lower().startswith(letra) == True:
          Fila = archivo4.loc[(archivo4["DESCRIPCION"] == i)]
          print(f"\n{Fila}\n")
          cont += 1

    else:
      for i in lista3:
        if N.lower() in i.lower():
          Fila = archivo4.loc[(archivo4["DESCRIPCION"] == i)]
          print(f"\n{Fila}\n")
          cont += 1

    print(f"hay {cont} {file} que coinciden con ese nombre\n")

  if tipo == "CodigoBarras":
    while True:
      lista2 = archivo4["CODIGO_BARRAS"].tolist()

      try:
        CB = int(input("introduce el codigo de barras :"))
      except ValueError:
        print("introduce solamente valores numericos enteros")
        continue

      if CB in lista2:
        Fila = archivo4.loc[(archivo4["CODIGO_BARRAS"] == CB)]
        print(f"\n{Fila}\n")
        break

      else:
        print("\nEste codigo de barras no existe,intentalo de nuevo\n")
        continue


Archivo = pd.read_excel("/content/drive/MyDrive/BaseUsuariosyProductos/Papeleria (2).xlsx")
Clientes = pd.read_excel("/content/drive/MyDrive/BaseUsuariosyProductos/CLIENTES.xlsx")
Proveedores = pd.read_excel("/content/drive/MyDrive/BaseUsuariosyProductos/PROVEEDORES.xlsx")

while True:
  print("Almacen")
  print("1:Productos\n2:Clientes\n3:Proveedores\n4:salir")
  try:
    BD = int(input("introduce a que base de datos quieres acceder :"))
  except ValueError:
    print("introduce un valor valido")
    continue
  if BD == 1:
    file = "Productos"

    while True:
      print("Base de datos de productos")
      print("1: Agregar producto\n2: Eliminar producto\n3: Modificar\n4: Buscar producto\n5: Exportar a Excel\n6: Imprimir\n7: Salir")
      try:
        op = int(input("introduce una opcion :"))
      except:
        print("introduce un valor valido")
        continue
      if op == 1:
        Archivo = Alta(Archivo,file)

      elif op == 2:
        Archivo = Eliminar(Archivo,file)

      elif op == 3:
        while True:

          print("1: Modificar descripcion, 2: Modificar codigo de barras, 3: Modificar stock, 4: Modificar precio, 5: Salir")
          try:
            Mod = int(input("introduce que quieres modificar :"))
          except ValueError:
            print("introduce un valor valido")
            continue

          if Mod == 1:
            Archivo = Modificar(Archivo, "DESCRIPCION",file)
          elif Mod == 2:
            Archivo = Modificar(Archivo, "CODIGO_BARRAS",file)
          elif Mod == 3:
            Archivo = Modificar(Archivo,"Stock",file)

          elif Mod == 4:
            Archivo = Modificar(Archivo,"PRECIO",file)

          elif Mod == 5:
            break

          else:
            print("Digita una eleccion valida!")

      elif op == 4:

        while True:
          print("1: Buscar por el codigo de barras, 2: Buscar por nombre, 3: Salir")
          try:
            buscmenu = int(input("Introduce la opcion que prefieras :"))
          except ValueError:
            print("introduce un valor valido")
            continue

          if buscmenu == 1:
            print("Buscar por codigo de barras")
            Buscar(Archivo, "CodigoBarras",file)

          elif buscmenu == 2:
            print("Buscar por nombre")
            Buscar(Archivo,"Nombre",file)

          elif buscmenu == 3:
            break

          else:
            print("Digita una opcion valida!")

      elif op == 5:
          Archivo.to_excel("/content/drive/MyDrive/BaseUsuariosyProductos/Papeleria (2).xlsx", index = False)
          print("Archivo exportado")

      elif op == 6:
        print("1: imprimir todos los productos, 2: imprimir solo uno, 3: salir")
        try:
          imppro = int(input("introduce que datos quieres imprimir :"))
        except ValueError:
            print("introduce un valor valido")
            continue
        if imppro == 1:
          Imprimir(Archivo,file)
        elif imppro == 2:
          CodigosLista = Archivo["CODIGO_BARRAS"].tolist()
          while True:
            try:
              Codigo = int(input("introduce el codigo de barras del producto a imprimir :"))
            except ValueError:
              print("introduce un valor valido")
              continue
            if Codigo in CodigosLista:
              Prod = Archivo.loc[(Archivo["CODIGO_BARRAS"] == Codigo)]
              Imprimir(Prod,file = "Producto")
              break
            else:
              print("codigo invalido, intentalo de nuevo")
              continue
        elif imppro == 3:
          break
      elif op == 7:
        break
      else:
        print("Introduce un numero valido")

  elif BD == 2:

    file = "Cliente"

    while True:

      print("CLIENTES")
      print("1: Agregar usuario\n2: Eliminar usuario\n3: Modificar\n4: Buscar usuario\n5: Exportar a Excel\n6: Imprimir\n7: Salir")
      try:
        y = int(input("introduce una opcion para acceder a la base de datos de usuarios :"))
      except ValueError:
            print("introduce un valor valido")
            continue
      if y == 1:
        Clientes = Alta(Clientes,file)

      elif y == 2:
        Clientes = Eliminar(Clientes,file)
      elif y == 3:
        while True:
          print("1:RFC\n2:Nombre\n3:Direccion\n4:Numero\n5:Correo\n6:salir")

          try:
            mod2 = int(input("introduce una opcion segun que quieras modificar :"))
          except ValueError:
            print("introduce un valor valido")
            continue

          if mod2 == 1:
            par = "RFC"
            Clientes = Modificar(Clientes,par,file)
          elif mod2 == 2:
            par = "NOMBRE"
            Clientes = Modificar(Clientes,par,file)
          elif mod2 == 3:
            par = "DIRECCION"
            Clientes = Modificar(Clientes,par,file)
          elif mod2 == 4:
            par = "NUMERO"
            Clientes = Modificar(Clientes,par,file)
          elif mod2 == 5:
            par = "CORREO"
            Clientes = Modificar(Clientes,par,file)
          elif mod2 == 6:
            break
          else:
            print("opcion invalida")

      elif y == 4:
        while True:
          print("1:RFC\n2:Nombre\n3:Salir")
          buscar2 = int(input("introduce una opcion segun como quieras buscar los datos :"))
          if buscar2 == 1:
            Buscar(Clientes,tipo = "RFC",file = file)
          elif buscar2 == 2:
            Buscar(Clientes, tipo = "NOMBRE", file = file)
          elif buscar2 == 3:
            break
          else:
            print("opcion invalida")
      elif y == 5:
        print("Exportar a excel\n")
        Clientes.to_excel("/content/drive/MyDrive/BaseUsuariosyProductos/CLIENTES.xlsx", index = False)
        print("Archivo generado\n")

      elif y == 6:
        while True:
          print("1:imprimir toda la base de datos a pdf\n2:imprimir solo un usuario\n3:salir")
          RFClis = Clientes["RFC"].tolist()
          imp = int(input("introduce una opcion :"))
          if imp == 1:
            Imprimir(Clientes,file)
          elif imp == 2:
            while True:
              RFCcliente = input(f"introduce el RFC del {file} :").upper().strip()
              if RFCcliente in RFClis:
                Cliente = Clientes.loc[(Clientes["RFC"] == RFCcliente)]
                Imprimir(Cliente,file = "Cliente")
                break
              else:
                print("este RFC no ha sido capturado, intentelo de nuevo")
                continue

      elif y == 7:
        break

      else:
        print("Opcion invalida")
  elif BD == 3:
    file = "Proveedor"
    while True:
      print("PROVEEDORES")
      print("1: Agregar usuario\n2: Eliminar usuario\n3: Modificar\n4: Buscar usuario\n5: Exportar a Excel\n6: Imprimir\n7: Salir")
      z = int(input("introduce una opcion para acceder a la base de datos de usuarios :"))

      if z == 1:
        Proveedores = Alta(Proveedores,file)

      elif z == 2:
        Proveedores = Eliminar(Proveedores,file)
      elif z == 3:
        while True:
          print("1:RFC\n2:Nombre\n3:Direccion\n4:Numero\n5:Correo\n6:salir")
          RFC = input("introduce el RFC del usuario que quieras modificar :")
          mod3 = int(input("introduce una opcion segun que quieras modificar :"))
          if mod3 == 1:
            par = "RFC"
            Proveedores = Modificar(Proveedores,par,file)
          elif mod3 == 2:
            par = "NOMBRE"
            Proveedores = Modificar(Proveedores,par,file)
          elif mod3 == 3:
            par = "DIRECCION"
            Proveedores = Modificar(Proveedores,par,file)
          elif mod3 == 4:
            par = "NUMERO"
            Proveedores = Modificar(Proveedores,par,file)
          elif mod3 == 5:
            par = "CORREO"
            Proveedores = Modificar(Proveedores,par,file)
          elif mod3 == 6:
            break
          else:
            print("opcion invalida")

      elif z == 4:
        while True:
          print("1:RFC\n2:Nombre\n3:Salir")
          buscar3 = int(input("introduce una opcion segun como quieras buscar los datos :"))
          if buscar3 == 1:
            Proveedores = Buscar(Proveedores,tipo = "RFC",file = file)
          elif buscar3 == 2:
            Clientes = Buscar(Proveedores, tipo = "NOMBRE", file = file)
          elif buscar3 == 3:
            break
          else:
            print("opcion invalida")
      elif z == 5:

        print("Exportar a excel\n")

        Proveedores.to_excel("/content/drive/MyDrive/BaseUsuariosyProductos/PROVEEDORES.xlsx", index = False)

        print("Archivo generado\n")

      elif z == 6:
        while True:
          print("1: imprimir toda la base de datos a pdf\n2:imprimir solo un usuario\n3:salir")
          imp2 = int(input("introduce una opcion :"))
          if imp2 == 1:
            Imprimir(Proveedores,file)
          elif imp2 == 2:
            RFClisP = Proveedores["RFC"].tolist()
            while True:
              RFCProveedor = input(f"introduce el RFC del {file} :").upper().strip()
              if RFCProveedor in RFClisP:
                Proveedor = Proveedores.loc[(Proveedores["RFC"] == RFCProveedor)]
                Imprimir(Proveedor,file= "Proveedor")
                break
              else:
                print("este RFC no ha sido capturado, intentelo de nuevo")
                continue
          elif imp2 == 3:
            break
          else:
            print("Introduce un valor valido")
      elif z == 7:
        break
      else:
        print("opcion invalida")
  elif BD == 4:
    print("Ejecucion terminada")
    break
  else:
    print("digita una opcion valida")